name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Install Upstream BCC Tools
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
        echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
        sudo apt update
        sudo apt install bcc-tools libbcc-examples linux-headers-$(uname -r)

    - name: Install Protobuf Compiler
      run: | 
        sudo apt install protobuf-compiler
        go get -u github.com/golang/protobuf/protoc-gen-go
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin

    - name: Generate BPF Sources
      run: go generate

    - name: Execute Tests
      run: go test ./...
      
    - name: Build
      run: go build -v .

    - name: Update AS Data
      run: ./updateASData.sh

    - name: Smoke Test
      run: sudo timeout --preserve-status --signal=INT 10s ./appfirewall

    - name: Create Build Artifact
      run: |
        mkdir -p dist/as
        mv ./appfirewall dist/
        mv ./README.md dist/
        mv as/ip2asn-v4-u32.tsv dist/as/
        mkdir artifacts
        tar czf artifacts/appfirewall.tar.gz --directory=dist/ .

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: appfirewall
        path: artifacts
